version: '3.4'

services:
  demoapp:
    image: ${DOCKER_REGISTRY-}demoapp
    build:
      context: .
      dockerfile: DemoApp/Dockerfile
    depends_on:
        - database
        - broker
    ports:
      - "80:80"
  demoworker:
    image: ${DOCKER_REGISTRY-}demoworker
    build:
      context: .
      dockerfile: DemoReceiver.Worker/Dockerfile
    depends_on:
        - broker
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
    - "1433:1433"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd"
      MSSQL_PID: "Express"
  broker:
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "90:80"
     - "8080:15672"